import type { DraftFlow } from "@flowcommit/shared";

export type Template = { id: string; title: string; blurb: string; description: string; flow: DraftFlow };

/** Starting points that work without any AI tool installed. */
export const TEMPLATES: Template[] = [
  {
    id: "auth",
    title: "Sign up and log in",
    blurb: "Email sign-up, log in, password reset",
    description: "Accounts for a web app: people sign up with email and password, log in, and reset a forgotten password.",
    flow: {
      name: "Sign up and log in",
      steps: [
        { id: "s1", kind: "start", title: "Visitor opens the app", instructions: "" },
        { id: "s2", kind: "decision", title: "Has an account?", instructions: "Check for a saved session first and skip straight to the dashboard if it's still valid." },
        { id: "s3", kind: "screen", title: "Sign-up form", instructions: "Ask for name, email and password. Password must be at least 8 characters. Show errors under each field." },
        { id: "s4", kind: "screen", title: "Log-in form", instructions: "Ask for email and password. Link to 'Forgot password?'. After 5 failed tries, wait 1 minute." },
        { id: "s5", kind: "api", title: "Create account", instructions: "Hash the password, reject emails that are already registered, start a session." },
        { id: "s6", kind: "api", title: "Check credentials", instructions: "Compare the password hash. Return the same error for a wrong email or password." },
        { id: "s7", kind: "data", title: "Users table", instructions: "id, name, email (unique), password_hash, created_at." },
        { id: "s8", kind: "screen", title: "Dashboard", instructions: "Greet the user by name and show a log-out button." },
        { id: "s9", kind: "end", title: "Signed in", instructions: "" },
      ],
      arrows: [
        { from: "s1", to: "s2", label: "" },
        { from: "s2", to: "s3", label: "No" },
        { from: "s2", to: "s4", label: "Yes" },
        { from: "s3", to: "s5", label: "" },
        { from: "s4", to: "s6", label: "" },
        { from: "s5", to: "s7", label: "" },
        { from: "s6", to: "s7", label: "" },
        { from: "s7", to: "s8", label: "" },
        { from: "s8", to: "s9", label: "" },
      ],
    },
  },
  {
    id: "store",
    title: "Online store checkout",
    blurb: "Products, cart, payment, order email",
    description: "A small online store: shoppers browse products, add them to a cart, pay by card and get an order confirmation email.",
    flow: {
      name: "Online store",
      steps: [
        { id: "s1", kind: "start", title: "Shopper lands on store", instructions: "" },
        { id: "s2", kind: "screen", title: "Product list", instructions: "Grid of products with photo, name and price. Filter by category." },
        { id: "s3", kind: "screen", title: "Cart", instructions: "List items with quantity controls and a running total. Keep the cart if the page reloads." },
        { id: "s4", kind: "screen", title: "Checkout form", instructions: "Shipping address and card details. Validate before sending." },
        { id: "s5", kind: "api", title: "Charge the card", instructions: "Create the payment with the payment provider. Never store card numbers." },
        { id: "s6", kind: "decision", title: "Payment succeeded?", instructions: "" },
        { id: "s7", kind: "data", title: "Save the order", instructions: "orders: id, items, total, address, status, created_at." },
        { id: "s8", kind: "screen", title: "Payment failed", instructions: "Explain what went wrong and let the shopper try another card without retyping the address." },
        { id: "s9", kind: "end", title: "Confirmation email sent", instructions: "Email the order summary and show a thank-you page." },
      ],
      arrows: [
        { from: "s1", to: "s2", label: "" },
        { from: "s2", to: "s3", label: "Add to cart" },
        { from: "s3", to: "s4", label: "" },
        { from: "s4", to: "s5", label: "" },
        { from: "s5", to: "s6", label: "" },
        { from: "s6", to: "s7", label: "Yes" },
        { from: "s6", to: "s8", label: "No" },
        { from: "s8", to: "s4", label: "Try again" },
        { from: "s7", to: "s9", label: "" },
      ],
    },
  },
  {
    id: "habits",
    title: "Habit tracker",
    blurb: "Daily check-ins and streaks",
    description: "A habit tracker: people add habits, check in once a day, and see their current streak for each habit.",
    flow: {
      name: "Habit tracker",
      steps: [
        { id: "s1", kind: "start", title: "User opens the app", instructions: "" },
        { id: "s2", kind: "decision", title: "Any habits yet?", instructions: "" },
        { id: "s3", kind: "screen", title: "Add a habit", instructions: "Name and an optional emoji. Suggest 3 common habits to tap." },
        { id: "s4", kind: "screen", title: "Today's habits", instructions: "One row per habit with a big check button and the current streak." },
        { id: "s5", kind: "api", title: "Record check-in", instructions: "One check-in per habit per day. Tapping again undoes it." },
        { id: "s6", kind: "data", title: "Check-ins", instructions: "habit_id, date (unique together), created_at." },
        { id: "s7", kind: "end", title: "Streak updated", instructions: "Animate the streak number going up." },
      ],
      arrows: [
        { from: "s1", to: "s2", label: "" },
        { from: "s2", to: "s3", label: "No" },
        { from: "s2", to: "s4", label: "Yes" },
        { from: "s3", to: "s4", label: "" },
        { from: "s4", to: "s5", label: "Check in" },
        { from: "s5", to: "s6", label: "" },
        { from: "s6", to: "s7", label: "" },
      ],
    },
  },
  {
    id: "chat",
    title: "AI chat assistant",
    blurb: "Chat history, streaming replies, usage limits",
    description: "A chat app where signed-in people talk to an AI assistant, see replies as they're written, and come back to earlier chats.",
    flow: {
      name: "AI chat assistant",
      steps: [
        { id: "s1", kind: "start", title: "Person opens the chat", instructions: "" },
        { id: "s2", kind: "screen", title: "Chat list", instructions: "Earlier chats in the sidebar, newest first, each titled from its first message. A New chat button at the top." },
        { id: "s3", kind: "screen", title: "Conversation", instructions: "Messages in bubbles, a text box that grows as you type, Enter to send and Shift+Enter for a new line." },
        { id: "s4", kind: "decision", title: "Under the daily limit?", instructions: "Each person can send 50 messages a day. Count messages since midnight in their time zone." },
        { id: "s5", kind: "api", title: "Ask the AI model", instructions: "Send the conversation so far to the AI model and stream the reply back word by word. Keep the API key on the server." },
        { id: "s6", kind: "data", title: "Save the messages", instructions: "chats: id, user_id, title, created_at. messages: id, chat_id, role (user or assistant), text, created_at." },
        { id: "s7", kind: "screen", title: "Limit reached", instructions: "Say how many messages are left tomorrow and when the limit resets. Keep earlier chats readable." },
        { id: "s8", kind: "end", title: "Reply shown", instructions: "" },
      ],
      arrows: [
        { from: "s1", to: "s2", label: "" },
        { from: "s2", to: "s3", label: "Open or start a chat" },
        { from: "s3", to: "s4", label: "Send" },
        { from: "s4", to: "s5", label: "Yes" },
        { from: "s4", to: "s7", label: "No" },
        { from: "s5", to: "s6", label: "" },
        { from: "s6", to: "s8", label: "" },
      ],
    },
  },
  {
    id: "booking",
    title: "Booking with a deposit",
    blurb: "Pick a service and time, pay a deposit",
    description: "A booking page for a small business: customers pick a service, a staff member and a time, pay a deposit, and get a reminder the day before.",
    flow: {
      name: "Bookings",
      steps: [
        { id: "s1", kind: "start", title: "Customer opens booking page", instructions: "" },
        { id: "s2", kind: "screen", title: "Choose a service", instructions: "Cards with each service's name, length and price." },
        { id: "s3", kind: "screen", title: "Pick a time", instructions: "A week view of free slots for the chosen service. Optionally pick a staff member, or 'anyone'." },
        { id: "s4", kind: "decision", title: "Slot still free?", instructions: "Check again just before paying, so two people can't book the same slot." },
        { id: "s5", kind: "api", title: "Take the deposit", instructions: "Charge 20% of the price through the payment provider. Refund it in full if cancelled 24 hours ahead." },
        { id: "s6", kind: "data", title: "Save the booking", instructions: "bookings: id, service_id, staff_id, starts_at, customer_name, email, phone, deposit_status." },
        { id: "s7", kind: "step", title: "Send reminders", instructions: "Email a confirmation now and a reminder 24 hours before, with a link to cancel or move the booking." },
        { id: "s8", kind: "screen", title: "Pick another time", instructions: "Say the slot was just taken and show the nearest free ones." },
        { id: "s9", kind: "end", title: "Booking confirmed", instructions: "" },
      ],
      arrows: [
        { from: "s1", to: "s2", label: "" },
        { from: "s2", to: "s3", label: "" },
        { from: "s3", to: "s4", label: "" },
        { from: "s4", to: "s5", label: "Yes" },
        { from: "s4", to: "s8", label: "No" },
        { from: "s8", to: "s3", label: "Try again" },
        { from: "s5", to: "s6", label: "" },
        { from: "s6", to: "s7", label: "" },
        { from: "s7", to: "s9", label: "" },
      ],
    },
  },
  {
    id: "team",
    title: "Team workspace",
    blurb: "Create a workspace, invite teammates, roles",
    description: "Team accounts for a web app: someone creates a workspace, invites teammates by email, and gives them a role.",
    flow: {
      name: "Team workspace",
      steps: [
        { id: "s1", kind: "start", title: "Owner signs in", instructions: "" },
        { id: "s2", kind: "screen", title: "Create a workspace", instructions: "Ask for a workspace name and make the person its owner." },
        { id: "s3", kind: "screen", title: "Invite teammates", instructions: "Type several emails at once and pick a role for them: admin or member." },
        { id: "s4", kind: "api", title: "Send invitations", instructions: "Email each person a link that works once and expires in 7 days." },
        { id: "s5", kind: "decision", title: "Already has an account?", instructions: "" },
        { id: "s6", kind: "screen", title: "Sign up from the invite", instructions: "Email is filled in from the invitation; ask only for name and password." },
        { id: "s7", kind: "data", title: "Members and roles", instructions: "workspaces: id, name, owner_id. members: workspace_id, user_id, role. invites: id, workspace_id, email, role, expires_at, used_at." },
        { id: "s8", kind: "screen", title: "Members page", instructions: "List members with their role. Owners and admins can change roles or remove people; nobody can remove the owner." },
        { id: "s9", kind: "end", title: "Teammate joined", instructions: "" },
      ],
      arrows: [
        { from: "s1", to: "s2", label: "" },
        { from: "s2", to: "s3", label: "" },
        { from: "s3", to: "s4", label: "" },
        { from: "s4", to: "s5", label: "Invite opened" },
        { from: "s5", to: "s6", label: "No" },
        { from: "s5", to: "s7", label: "Yes" },
        { from: "s6", to: "s7", label: "" },
        { from: "s7", to: "s8", label: "" },
        { from: "s8", to: "s9", label: "" },
      ],
    },
  },
];
